application: brainlogger-mapmate
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: html/js

- url: /css
  static_dir: html/css
  
- url: /img
  static_dir: html/img
    
- url: /mf
  static_dir: html/mf
  mime_type: text/cache-manifest 

- url: /
  static_files: html/index.html
  upload: html/index.html
  
- url: /.*
  script: main.py
